name: alzheimer_classifier
description: Clasificador Alzheimer con CNN - Examen Parcial
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # file_picker funciona mejor que image_picker en Flutter Web
  file_picker: ^8.0.3
  http: ^1.2.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
